root = "."
tmp_dir = "build"
[build]
  cmd = "pnpm build && go build -o ./build/main"
  bin = "./build/main"
  args_bin = ["-task", "serve"]
  delay = 1000
  exclude_dir = ["build", "node_modules"]
  include_ext = ["go", "html", "tsx", "ts"]
  exclude_regex = ["_test\\.go"]
