# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  init:
    cmds:
      - go generate ./...
  
  gqlgen:
    cmds:
      - cd pkg/invoke && go run github.com/99designs/gqlgen generate
      - cd ctlweb && pnpm gqlgen

  fmt:
    cmds:
      - go fmt ./...
      - cd ctlweb && pnpm format
