name: ci

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        with:
          version: '9'

      - run: go generate ./...
      - run: go test ./...
      - run: go build -o walkhttp

      - uses: actions/upload-artifact@v4
        with:
          name: walkhttp
          path: walkhttp

  gqle2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: walkhttp
      
      - run: chmod +x ./walkhttp
      - run: |
          ./walkhttp > a.log 2>&1 &
          sleep 1

      - uses: gacts/install-hurl@v1
      - run: hurl gqle2e/basic.hurl

      - run: cat a.log
