name: ci

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - uses: pnpm/action-setup@v4
        with:
          version: '9'

      - run: go generate ./...
      - run: go install
      - run: go test ./...

      - working-directory: ctlweb
        run: pnpm install
      - name: validate graphql documents
        working-directory: ctlweb
        run: pnpm gen:gql
